### ISSUE TITLE
Polymer depreciation 

### ISSUE THREAD

**Issue by Madj42** [finity69x2/cover-control-button-row#10]
This appears to use polymer.  https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

**Comment by abeltman** [comment]
I confirm that the element no longer works after upgrading to 2023.5(.1). Hope that it can be updated so that I can continue to use the cover control button row.

**Comment by finity69x2** [comment]
I'm working on it.

the polymer deprecation caught me off guard with such little notice and I have to figure out how to update it.

**Comment by finity69x2** [comment]
It should be fixed now.
