### ISSUE TITLE
Remove STOP button?

### ISSUE THREAD

**Issue by psperry** [finity69x2/cover-control-button-row#5]
Is there a way to eliminate the Stop button? My garage door does not support this funtion.

**Comment by finity69x2** [comment]
I'm sorry, no, not without rewriting the controls. I really don't want to do that tho.

Right now it should be similar to the built-in cover control functionality. If you don't use my plug-in what does that built-in control look like? Does it have the stop button too?

**Comment by psperry** [comment]
Bummer. The built in control just has an up or down arrow, which I am afraid might confuse my feeble minded users. I think I will stick with your control even though the stop button doesn't do anything. Thanks for your work on this. 

![image](https://user-images.githubusercontent.com/5041558/100656584-edfed800-331a-11eb-896d-027eb21c765a.png)

![image](https://user-images.githubusercontent.com/5041558/100656694-14247800-331b-11eb-93c6-c0da0b356244.png)

**Comment by finity69x2** [comment]
Wow, I guess I've never seen that the built-in one doesn't always have the stop cover button. Since both of my covers support the stop I assumed they all did.

You might have just talked me into trying to be able to make that able to be hidden.

I'll let you know if it's doable. 

Thanks for letting me know about this.

**Comment by finity69x2** [comment]
well, that was way easier than I thought.

the update is in the repo now and hopefully the release will hit HACS in a little while.

Please, let me know if it works OK.

**Comment by psperry** [comment]
Hmmm, updated using HACS and confirmed the new file hit my config but the same three buttons still show even after clearing the browser cache and rebooting HA. Let me know how I can help further. Thanks again!

**Comment by jasonalsing** [comment]
I had the same problem but it eventually 'disappeared' after I did a shift-F5 reload. But I did notice my  control is not in a 'card' ie it doesn't have the nice rounded box with white background:

![image](https://user-images.githubusercontent.com/38263272/100771508-1b539080-33c4-11eb-8dff-b7dea9179ca9.png)

**Comment by psperry** [comment]
I hit ctr-f5 at least a dozen times and all three buttons appear in every browser I've tied and the iPhone app too. I even tried reinstalling but no change.

**Comment by finity69x2** [comment]
Did you update the config with the new option "isTwoSpeedFan: true"?

**Comment by finity69x2** [comment]
@jasonalsing 

Could you post your card config, please?

Mine is working fine here for me.

**Comment by psperry** [comment]
Working perfectly now. Helps if you read the new config instructions. Duh.

![image](https://user-images.githubusercontent.com/5041558/100786635-6bd8e700-33e0-11eb-805e-0775beac0272.png)

**Comment by jasonalsing** [comment]
> @jasonalsing
> 
> Could you post your card config, please?
> 
> Mine is working fine here for me.

I got it figured out, it was not embedded within an entities card, I had added it standalone (odd that it still works)

**Comment by finity69x2** [comment]
Thanks for testing it for me.

Closing.
