### ISSUE TITLE
Close button does not work on Lightwave relay

### ISSUE THREAD

**Issue by raypanggh** [finity69x2/cover-control-button-row#7]
Open and stop buttons work on Lightwave relay (represented as a cover entity). Close doesn't work.

**Comment by finity69x2** [comment]
If you close the cover what service does the cover use?

If you call the service "cover.close_cover" for your cover entity does that work?

**Comment by raypanggh** [comment]
> If you close the cover what service does the cover use?
> 
> If you call the service "cover.close_cover" for your cover entity does that work?

Yes, it seems to work when I call the close_cover service. The standard "up/stop/down" control works ok.

{
    "event_type": "call_service",
    "data": {
        "domain": "cover",
        "service": "close_cover",
        "service_data": {
            "entity_id": "cover.bedroom_curtains"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-05-03T21:33:08.380264+00:00",
    "context": {
        "id": "4e0c68e5bac5327d7549021e89e98b7d",
        "parent_id": null,
        "user_id": "bf32fe2d83a643d6a3fc8c3e71249f82"
    }
}

**Comment by finity69x2** [comment]
What are the states of the cover in the different positions?

"closed" & "open" or something else?
