### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by danb5** [finity69x2/cover-control-button-row#8]
Is it possible to have the button that is being pressed flash on press or change color momentarily on press so when Opening remotely it is clear that the button press was successful.  Sometimes my phone does not respond to a touch and requires a second tap and it would be nice to know if the button recognized the tap or not or if the screen didn’t recognized the touch.

**Comment by finity69x2** [comment]
mine actually does give a bit of a color change on my Galaxy S21 when I press it.

as far as haptic feedback I believe that is controlled by HA itself and was added in v0.99. But then again my phone doesn't vibrate when I push the button on my mobile app either and I have no idea how to find out why not.

So I guess the answer is that I don't think I can do anything more on my end. But that is likely my lack of knowledge on the subject as I'm not really a programmer. I just dabbled enough to get this done and figured it out as I went along. :)
